# Default Values for go-web-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ramkumar222/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag. Default is the chart appVersion.
  tag: "12512413677"

ingress:
  enabled: false
  className: ""
  annotations: {}
  
  # Kubernetes Ingress class and annotations (if needed):
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
